### ISSUE TITLE
Support for Chrome Debugging Protocol 1.2

### ISSUE THREAD

**Issue by wildbook** [MasterDevs/ChromeDevTools#14]
As you may know the protocol.json file is now [split into two different files](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/protocol.json?q=protocol.json&sq=package:chromium&type=cs&l=1), browser_protocol.json and js_protocol.json.
Would it be possible to add support for 1.2?

(Or did I miss something?)

**Comment by georgiosd** [comment]
Check my pull request - I fixed that
