### ISSUE TITLE
Build failing , Unable to find version '1.0.3' of package 'CoolWhip'.	MasterDevs.ChromeDevTools

### ISSUE THREAD

**Issue by dheeraj2016** [MasterDevs/ChromeDevTools#31]
HI , 

Just downloaded release 1.1.0 and tried to build, and got below error 
Unable to find version '1.0.3' of package 'CoolWhip'.	MasterDevs.ChromeDevTools
please help 

thank you 
Dheeraj Kumar

**Comment by cResults** [comment]
I ran into the same thing. basically the MasterDevs.ChromeDevTools.csproj was created with an older version of nuget than what you have installed.  The way I fixed this was to delete the following lines from the csproj file

`<Import Project="$(SolutionDir)\.nuget\NuGet.targets" Condition="Exists('$(SolutionDir)\.nuget\NuGet.targets')" />`

`<Error Condition="!Exists('$(SolutionDir)\.nuget\NuGet.targets')" Text="$([System.String]::Format('$(ErrorText)', '$(SolutionDir)\.nuget\NuGet.targets'))" />`

I also made changes to the NuGet.Config to include:
`  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <packageRestore>
    
    <add key="enabled" value="True" />
    
    <add key="automatic" value="True" />
  </packageRestore>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>`

**Comment by cResults** [comment]
it seems to me that I ran into errors in other projects once this one built.  Let me know what you run into and i'll do my best to help.

**Comment by dheeraj2016** [comment]
I removed it and able to build solution , but sample is not working and giving below error
System.Exception: 'Don't know what to do with response: {"method":"Page.lifecycleEvent","params":{"frameId":"(412E7D0A117C93FFC92F3C578AC2B6CD)","name":"firstPaint","timestamp":70603.599485}}'

i have no idea what this mean , can you please help . 
this is very urgent for me ... Please help

**Comment by cResults** [comment]
I'm sorry for slow response.  just now seeing your question.  

If you Find "Don't know what to do with response" there appears to only be two places this can be thrown.  There must be some change that you have made that is resulting in this behavior.  LifecycleEventEvent is in the Chrome.Page namespace.  It is a Chrome event that you can subscribe to that is "Fired for top level page lifecycle events such as navigation, load, paint, etc."

I realize I'm not telling what you haven't already figured out, but I'm just learning this library myself and haven't yet run into that error.

**Comment by Dheerajmentor** [comment]
Thanks for reply , i did not change anything except i build it in visual studio and tried to run it .
but it keeps failing. My browser's version is 63 , can that be the problem ?
please help

**Comment by dheeraj2016** [comment]
I did not change anything except i removed "CoolWhip" from package.config file and build it. 
i really need this working. 
please help. 

thank you 
Dheeraj Kumar

**Comment by cResults** [comment]
Are you trying to run the sample project?  it subscribes to the LoadEventFiredEvent on line 54 of Program.cs.  That seems to be the event that is throwing the error.  You may want to search Chrome's docs for what can cause this failure.  It appears that ChromeDevTools is just rethrowing the error it gets back from Chrome.  I'm speculating here since once ChromeDevTools compiled on my machine, the Sample program worked.

Seems like there is something different in your environment that causing this.

**Comment by svatal** [comment]
The error "Don't know what to do with response .." means that that chrome sent data the have not counterpart in Protocol. In other words, the library does not know how to deserialize the message. 
I've run into this issue myself when using chrome 52 with protocol build from chrome 50. I've pending PR with changes that could lover fatality of such issue, until then I suggest keeping the protocol files updated.

**Comment by brewdente** [comment]
I've fixed this issue with the latest commit. 049ba9e
